PikPay/PikPay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from api.routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('auth/',include('authen.urls')),
    path('',include('shop.urls')),
    path('api/v1/', include(router.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PikPay/authen/urls.py
from django.urls import path
from .views import login,home,logout,register,zipcode,amphur

app_name = 'authen'
urlpatterns = [
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),
    path('home/',home,name='home'),
    path('register/',register,name='register'),

    # API #
    path('zipcode/',zipcode),
    path('amphur/',amphur),
]

PikPay/shop/urls.py
from django.urls import path
from .views import *
# from .views import home,homeandlifestyle,fashion,healthandbeauty,sportsandtravel,groceriesandpets,toys,electronics,profile,sell

app_name = 'shop'

urlpatterns = [
    path('',home,name='home'),
    path('homeandlifestyle/',homeandlifestyle,name='homeandlifestyle'),
    path('fashion/',fashion,name='fashion'),
    path('healthandbeauty/',healthandbeauty,name='healthandbeauty'),
    path('sportsandtravel/',sportsandtravel,name='sportsandtravel'),
    path('groceriesandpets/',groceriesandpets,name='groceriesandpets'),
    path('toys/',toys,name='toys'),
    path('electronics/',electronics,name='electronics'),
    path('justforyou/',justforyou,name='justforyou'),
    path('profile/',profile,name='profile'),
    path('shipping-address/',shippingaddress,name='shippingaddress'),
    path('sellverify/',sellverify,name='sellverify'),
    path('sellhome/',sellhome,name='sellhome'),
    path('mysell/',mysell,name='mysell'),
    path('sellerorder/<int:pk>',sellerorder,name='sellerorder'),
    path('seller_confirm/<int:pk>',seller_confirm,name='seller_confirm'),
    path('myproduct/',myproduct,name='myproduct'),
    path('addproduct/',addproduct,name='addproduct'),
    path('sellwallet/',sellwallet,name='sellwallet'),
    path('product/<int:pk>',product,name='product'),
    path('editprofile/',editprofile,name='editprofile'),
    path('creditcard/',creditcard,name='creditcard'),
    path('del_card/<int:pk>',delete_card,name='delete_card'),
    path('order/',order,name='order'),
    path('cancle_order/<int:pk>',cancle_order,name='cancle_order'),
    path('del_shippingaddr/<int:pk>/<str:page>',del_shippingaddress,name='del_shippingaddress'),
    path('set_dault_shippingaddress/<int:pk>/<str:page>',set_dault_shippingaddress,name='set_dault_shippingaddress'),
    path('reviewproduct/<int:pk>',reviewproduct,name='reviewproduct'),
    path('myfavourite/',myfavourite,name='myfavourite'),
    path('add_favorite/<int:pk>',add_favorite,name='add_favorite'),
    path('mycart/',mycart,name='mycart'),
    path('shoppinginfo/',shoppinginfo,name='shoppinginfo'),
    path('seller/',seller,name='seller'),
    path('search/',search,name='search'),
    path('shop/api/mybuck/',mybucket,name='mybucket'),
    path('del_bucket/<int:pk>',del_bucket,name='del_bucket'),
    path('confirmshipping/',confirmshipping,name='confirmshipping'),
    path('tracking/<int:pk>',tracking,name='tracking'),
    path('editaddress/',editaddress,name='editaddress'),
    path('upload_product_pic/',upload_picture,name='upload_pic'),
    path('editproduct/<int:pk>',edit_product,name='edit_product'),
    path('review/',review,name='review'),
    path('confirm_order/<int:pk>',confirm_order,name='confirm_order'),
    path('shop_product/<int:pk>',shop_product,name='shop_product'),
    path('del_product/<int:pk>',del_product,name='del_product'),
]

PikPay/authen/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in
from django.shortcuts  import redirect
# Create your models here.

class Account(models.Model):
    user = models.OneToOneField(User,on_delete=models.PROTECT)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    dob = models.DateField(auto_now=False, auto_now_add=False,null=True)
    image = models.ImageField(null=True)
    GENDER_CHOICE = [
        ('m','male'),
        ('f','female'),
        ('r','Rather not say')
    ]
    gender = models.CharField(max_length=1,choices =GENDER_CHOICE)
    def __str__(self):
        return "{}-{}_{}".format(self.user,self.first_name,self.last_name)

class Provinces(models.Model):
    name_th = models.CharField(max_length=100)
    name_en = models.CharField(max_length=100)
    def __str__(self):
        return "{}/{}".format(self.name_th,self.name_en)
    
class Amphurs(models.Model):
    amphur_id = models.PositiveSmallIntegerField()
    province = models.ForeignKey(Provinces,on_delete=models.CASCADE)
    name_th = models.CharField(max_length=100)
    name_en = models.CharField(max_length=100)

class Districts(models.Model):
    amphur = models.ForeignKey(Amphurs,on_delete=models.CASCADE)
    name_th = models.CharField(max_length=100)
    name_en = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5)

    def __str__(self):
        return "{} {} {} {}".format(self.name_th,self.amphur.name_th,self.amphur.province.name_th,self.zipcode)
    

class Address(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address1 = models.TextField()
    address2 = models.ForeignKey(Districts,on_delete=models.CASCADE)
    account = models.ForeignKey(Account,on_delete=models.CASCADE)
    is_use = models.BooleanField(default=False)

    def getAddr(self):
        return "{} {} | {} {} {} {} {}".format(
                self.name,
                self.phone,
                self.address1,
                self.address2.name_th,
                self.address2.amphur.name_th,
                self.address2.amphur.province.name_th,
                self.address2.zipcode)
def logged_in_handle(sender, user, request, **kwargs):
    index = User.objects.filter(username=request.user)[0]
    profile = Account.objects.filter(user=request.user)
    if not profile.exists():
        print("not have profile")
        create_init_profile = Account.objects.update_or_create(
            user = index,
            first_name = index.first_name,
            last_name = index.last_name,
        )
user_logged_in.connect(logged_in_handle)

PikPay/authen/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout as signout, login as auth_login
from django.contrib.auth.models import User
from .models import Districts,Amphurs
from django.http import JsonResponse
# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request,user,backend='django.contrib.auth.backends.ModelBackend')
            return redirect('shop:home')
        else:
            context = {'msg':'Invalid Username or Password'}
            return render(request, 'authen/login.html',context)
    return render(request, 'authen/login.html')

def logout(request):
    signout(request)
    return redirect(reverse('shop:home'))

def register(request):
    if request.method == 'POST':
        username    = request.POST['registeredUsername']
        password    = request.POST['registeredPassword']
        db_user     = User.objects.filter(username=username)
        if not db_user.exists(): 
            print("don't have user")
            user = User.objects.create_user(
                username = username,
                password = password,
            )
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('shop:home')
        else:
            # return redirect('shop:home')
            context = {'msg':'Username have exists please use other'}
            return render(request, 'authen/login.html',context)  
    else:
        return render(request, 'authen/login.html')

@login_required
def home(request):
    return render(request, 'authen/home.html')

def zipcode(request):
    district = list(Districts.objects.filter(zipcode=request.GET.get('zipcode')).values('name_en','name_th','amphur','pk'))
    return JsonResponse(district,safe=False)

def amphur(request):
    amphur = list(Districts.objects.filter(pk=int(request.GET.get('amphur'))).values('amphur__name_en','amphur__name_th','amphur__province__name_th','amphur__province__name_en'))
    return JsonResponse(amphur,safe=False)

PikPay/authen/templates/authen/base.html
    <!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>Social Auth with Django</title>
</head>
<body>
    <div class="container-fluid">
        <div>
            <h1 class="text-white text-center">{% block title %}{% endblock %}</h1>
            <div class="card p-5">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

PikPay/authen/templates/authen/home.html
 <!-- templates/home.html -->
 {% extends 'authen/base.html' %}
 {% block title %} Home {% endblock %}
 {% block content %}
 <div class="row">
     <div class="col-sm-12 mb-3">
         <h4 class="text-center"> Welcome {{ user.username }} </h4>
     </div>
 </div>
 {% endblock %}

PikPay/authen/templates/authen/login.html
<!-- templates/login.html -->

{% load static %}
<!-- {% block title %} Sign in {% endblock %} -->

{% block static %}
<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'css/authen-style.css' %}" type="text/css" />

	<script src="{% static 'js/uikit.min.js' %}"></script>
	<script src="{% static 'js/uikit-icons.min.js' %}"></script>
	<!-- <link href="https://fonts.googleapis.com/css?family=Kanit" rel="stylesheet"> -->
	<link href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit:300,400,500,700&amp;subset=thai">
	<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>


{% endblock static %}
{% block content %}
<body>
	<div id="auth-form" class="uk-flex uk-flex-center uk-flex-middle">
		<div class="uk-card uk-card-default uk-card-body uk-width-1-2@s uk-width-1-3@l uk-width-1-4@xl">
			<a class="uk-navbar-item uk-logo" href="/"><img src="{% static 'img/logo.png' %}" width="300"></a>
			<ul class="uk-flex-center" uk-tab>
				<li class="uk-active"><a>เข้าสู่ระบบ</a></li>
				<li><a>สมัครสมาชิก</a></li>
			</ul>

			<ul class="uk-switcher">
				<li>
					<!-- <form method="POST" action="{% url 'authen:login' %}"> -->
					<form method="POST">
						{% csrf_token %}
						<div class="uk-margin-small">
							<h3 style="color: red;">{{msg}}</h3>
							<label class="uk-form-label" for="username">ชื่อผู้ใช้งาน</label>
							<div class="uk-form-controls">
								<input class="uk-input" id="username" type="text" placeholder="ชื่อผู้ใช้งาน" name="username" required>
							</div>
						</div>
						<div class="uk-margin-small">
							<label class="uk-form-label" for="password">รหัสผ่านผู้ใช้</label>
							<div class="uk-form-controls">
								<input class="uk-input" id="password" type="password" placeholder="รหัสผ่านผู้ใช้" name="password" required>
							</div>
						</div>
						<button class="uk-button uk-button-primary uk-width-1-1 uk-text-center" type="submit">เข้าสู่ระบบ</button>
					</form>
				</li>
				<li>
					<form method="POST" action="/auth/register/">
						{% csrf_token %}
						<div class="uk-margin-small">
							<label class="uk-form-label" for="registeredUsername">ชื่อผู้ใช้งาน</label>
							<div class="uk-form-controls">
								<input class="uk-input" id="registeredUsername" type="text" placeholder="ชื่อผู้ใช้งาน" name="registeredUsername"
								 required>
							</div>
						</div>
						<div class="uk-margin-small">
							<label class="uk-form-label" for="registeredPassword">รหัสผ่านผู้ใช้</label>
							<div class="uk-form-controls">
								<input class="uk-input" id="registeredPassword" type="password" v-model="password" placeholder="รหัสผ่านผู้ใช้"
								 name="registeredPassword" required>
							</div>
						</div>
						<div class="uk-margin-small">
							<label class="uk-form-label" for="confirmRegisteredPassword">ยืนยันรหัสผ่านผู้ใช้</label>
							<div class="uk-form-controls">
								<input class="uk-input" id="confirmRegisteredPassword" type="password" v-model="confirmedPassword" placeholder="ยืนยันรหัสผ่านผู้ใช้"
								 name="confirmRegisteredPassword" required>
							</div>
						</div>
						<button class="uk-button uk-button-primary uk-width-1-1 uk-text-center" type="submit" :disabled="!isPasswordMatch">สมัครสมาชิก</button>
					</form>
				</li>
			</ul>

			<hr class="uk-divided">
			<a class="uk-button uk-width-1-1 facebook" href="{% url 'social:begin' 'facebook' %}">
				<i class="fab fa-facebook-square fa-2x uk-text-top"></i> เข้าสู่ระบบด้วยบัญชี FACEBOOK
			</a>

			<a class="uk-button uk-width-1-1 google" href="{% url 'social:begin' 'google-oauth2' %}">
				<i class="fab fa-google fa-2x uk-text-top"></i> เข้าสู่ระบบด้วยบัญชี Google
			</a>
		</div>
	</div>
	<script>
		new Vue({
			el: '#auth-form',
			data: {
				password: null,
				confirmedPassword: null
			},
			computed: {
				isPasswordMatch() {
					return this.password !== null && this.password === this.confirmedPassword
				}
			}
		})
	</script>
</body>
{% endblock %}