PikPay/PikPay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from api.routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('auth/',include('authen.urls')),
    path('',include('shop.urls')),
    path('api/v1/', include(router.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PikPay/shop/urls.py
from django.urls import path
from .views import *
# from .views import home,homeandlifestyle,fashion,healthandbeauty,sportsandtravel,groceriesandpets,toys,electronics,profile,sell

app_name = 'shop'

urlpatterns = [
    path('',home,name='home'),
    path('homeandlifestyle/',homeandlifestyle,name='homeandlifestyle'),
    path('fashion/',fashion,name='fashion'),
    path('healthandbeauty/',healthandbeauty,name='healthandbeauty'),
    path('sportsandtravel/',sportsandtravel,name='sportsandtravel'),
    path('groceriesandpets/',groceriesandpets,name='groceriesandpets'),
    path('toys/',toys,name='toys'),
    path('electronics/',electronics,name='electronics'),
    path('justforyou/',justforyou,name='justforyou'),
    path('profile/',profile,name='profile'),
    path('shipping-address/',shippingaddress,name='shippingaddress'),
    path('sellverify/',sellverify,name='sellverify'),
    path('sellhome/',sellhome,name='sellhome'),
    path('mysell/',mysell,name='mysell'),
    path('sellerorder/<int:pk>',sellerorder,name='sellerorder'),
    path('seller_confirm/<int:pk>',seller_confirm,name='seller_confirm'),
    path('myproduct/',myproduct,name='myproduct'),
    path('addproduct/',addproduct,name='addproduct'),
    path('sellwallet/',sellwallet,name='sellwallet'),
    path('product/<int:pk>',product,name='product'),
    path('editprofile/',editprofile,name='editprofile'),
    path('creditcard/',creditcard,name='creditcard'),
    path('del_card/<int:pk>',delete_card,name='delete_card'),
    path('order/',order,name='order'),
    path('cancle_order/<int:pk>',cancle_order,name='cancle_order'),
    path('del_shippingaddr/<int:pk>/<str:page>',del_shippingaddress,name='del_shippingaddress'),
    path('set_dault_shippingaddress/<int:pk>/<str:page>',set_dault_shippingaddress,name='set_dault_shippingaddress'),
    path('reviewproduct/<int:pk>',reviewproduct,name='reviewproduct'),
    path('myfavourite/',myfavourite,name='myfavourite'),
    path('add_favorite/<int:pk>',add_favorite,name='add_favorite'),
    path('mycart/',mycart,name='mycart'),
    path('shoppinginfo/',shoppinginfo,name='shoppinginfo'),
    path('seller/',seller,name='seller'),
    path('search/',search,name='search'),
    path('shop/api/mybuck/',mybucket,name='mybucket'),
    path('del_bucket/<int:pk>',del_bucket,name='del_bucket'),
    path('confirmshipping/',confirmshipping,name='confirmshipping'),
    path('tracking/<int:pk>',tracking,name='tracking'),
    path('editaddress/',editaddress,name='editaddress'),
    path('upload_product_pic/',upload_picture,name='upload_pic'),
    path('editproduct/<int:pk>',edit_product,name='edit_product'),
    path('review/',review,name='review'),
    path('confirm_order/<int:pk>',confirm_order,name='confirm_order'),
    path('shop_product/<int:pk>',shop_product,name='shop_product'),
    path('del_product/<int:pk>',del_product,name='del_product'),
]

PikPay/shop/views.py
from django.shortcuts               import render,redirect,HttpResponse
from django.http                    import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator          import Paginator, EmptyPage, PageNotAnInteger
from django.db.models               import Count,Sum,Avg

from .models        import Product, Category, Detail, Bucket, Buyer, CreaditCard, \
                            Transaction, Favorite, FlashSale,Logistic,Seller,Bank, \
                            Review, Picture
from authen.models  import Account,Address,Districts
from django.views.decorators.csrf import csrf_exempt

import calendar
import datetime
import random
ITEMS_PER_PAGE = 18 

# Create your views here.
def home(request):
    # Querry
    try:
        user = Account.objects.get(user=request.user)
    except Exception:
        pass
    else:
        if len(user.first_name)<=0 and len(user.phone)<=0:
            return redirect('shop:editprofile')
    best_sale = Product.objects.filter(is_use=True).order_by('-sales')[:4]
    flash_sale = FlashSale.objects.filter(date=datetime.datetime.now())
    try:
        favourite = Favorite.objects.filter(user__account__user=request.user,is_use=True).values('product__pk','product__category__pk')
    except Exception as e:
        print(e)
        hot_promotion = best_sale
        justforyou = best_sale
    else:
        product_pk = [x['product__pk'] for x in favourite]
        hot_product = Product.objects.filter(pk__in=product_pk,is_use=True).order_by('-sales')
        hot_promotion = hot_product | best_sale

        category_pk = [x['product__category__pk'] for x in favourite]
        justforyou = Product.objects.filter(category__pk__in=category_pk,is_use=True)[:ITEMS_PER_PAGE]
    try:
        context = {'first':best_sale[0],
                    'second':best_sale[1],
                    'best_sale':best_sale[2:],
                    'third':best_sale[3],
                    'hot_promotion':hot_promotion[:10],
                    'hot_promotion_mobile':hot_promotion[:3],
                    'flash_sale':flash_sale,
                    'justforyou':justforyou,
                    'today':datetime.datetime.now().strftime("%Y-%m-%dT23:59:59+07:00"),
                }
    except Exception as e:
         context = {}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/Home.html',context)
    else:
        return render(request,'shop/web/Home.html',context)

def homeandlifestyle(request):
    category = Category.objects.filter(name='homeandlifestyle')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}

    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_lifestyle.html',context)
    else:
        return render(request,'shop/web/HomeAndLifestyle.html',context)

def fashion(request):
    category = Category.objects.filter(name='fashion')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_fashion.html',context)
    else:
        return render(request,'shop/web/Fashion.html',context)

def healthandbeauty(request):
    category = Category.objects.filter(name='healthandbeauty')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_beauty.html',context)
    else:
        return render(request,'shop/web/HealthAndBeauty.html',context)

def sportsandtravel(request):
    category = Category.objects.filter(name='sportsandtravel')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_sport.html',context)
    else:
        return render(request,'shop/web/SportsAndTravel.html',context)

def groceriesandpets(request):
    category = Category.objects.filter(name='groceriesandpets')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_pet.html',context)
    else:
        return render(request,'shop/web/GroceriesAndPets.html',context)

def toys(request):
    category = Category.objects.filter(name='toys')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_toy.html',context)
    else:
        return render(request,'shop/web/Toys.html',context)

def electronics(request):
    category = Category.objects.filter(name='electronics')[0]
    product = Product.objects.filter(category=category,is_use=True)
    page    = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_electronic.html',context)
    else:
        return render(request,'shop/web/Electronics.html',context)

def justforyou(request):
    # category = Category.objects.filter(name='electronics')[0]
    # product = Product.objects.filter(category=category)
    '''wait for just for you algorithm'''
    product = Product.objects.filter(is_use=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(product, ITEMS_PER_PAGE)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'product':data}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/page_justforu.html',context)
    else:
        return render(request,'shop/web/JustForYou.html',context)
        
@login_required
def profile(request):
    profile = Account.objects.get(user=request.user)
    now_year = datetime.datetime.now().year
    address = Address.objects.filter(account=profile).order_by('-is_use')
    creadit_card = CreaditCard.objects.filter(account=profile)
    context = {'profile':profile,
                'address':address,
                'creadit_card':creadit_card,
                'month':["%02d"%m for m in range(1,13)],
                'year':["%02d"%y for y in range(now_year+10)],
            }
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/profile.html',context)
    else:
        return render(request,'shop/web/Profile.html',context)

@login_required
def editprofile(request):
    if request.method == 'POST':
        account = Account.objects.get(user=request.user)
        data = request.POST
        name = data['name'].split(' ')
        account.first_name  = name[0]
        account.last_name   = name[-1]
        account.phone       = data['phone']
        account.gender      = data['gender']
        dob = "{}-{}-{}".format(data['year'],data['month'],data['day'])
        account.dob = datetime.datetime.strptime(dob,"%Y-%B-%d").date()
        account.save()
        return redirect('shop:profile')
    profile  = Account.objects.get(user=request.user)
    now_year = datetime.datetime.now().year
    context  = {'profile':profile,
                'day':[i+1 for i in range(31)],
                'month':[(i,calendar.month_name[i]) for i in range(1,13)],
                'year':[i for i in range(1900,now_year+1)]}
    if request.user_agent.is_mobile:
        return render(request,'shop/mobile/editProfile.html',context)
    else:
        return render(request,'shop/web/EditProfile.html',context)

@login_required
def shippingaddress(request):
    profile = Account.objects.get(user=request.user)
    if request.method == 'POST':
        data = request.POST
        use  = False
        if 'seva_as_default' in data:
            if data['seva_as_default'] == 'on':
                use = True
                for x in Address.objects.filter(account=profile):
                    x.is_use = False
                    x.save()
            Address.objects.all().is_use = False

PikPay/shop/templates/shop/mobile/editAddress.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- UIkit CSS -->
        <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" type="text/css"/>

        <!-- UIkit JS -->
        <script src="{% static 'js/uikit.min.js' %}"></script>
        <script src="{% static 'js/uikit-icons.min.js' %}"></script>

        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/editaddress.css' %}">

        
        <title>Edit Address</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'img/logofinal.png' %}">
        
    </head>
    <body>
        <style type="text/css" >
            
           
        </style>
        <!-- Name Phone Province District Zipcode Address -->
        <a href="{% url 'shop:home' %}" class="back-button">< BACK</a>
        <br><br><br>
        <div class="white-bg">
            <div class="credit-head">
                <p>MY Profile</p>
                <hr>
            </div>
            <div class="credit-bg">
                <div class="uk-grid-column-small uk-grid-row-large uk-child-width-1-2@s uk-text-center"style="margin-left:3%; width: 90%;margin-top:-2%; "; uk-grid>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body" style="width: 80%; text-align: left; margin-top: 3%;box-shadow: none; background-color: #F7F5F5;" >
                            <div class="uk-margin">
                                <p style="padding-bottom: 10%;">Name</p>
                            </div>
                            <div class="uk-margin">
                                <p style="padding-bottom: 10%;">Phone</p>
                            </div>
                            <div class="uk-margin">
                                <p style="padding-bottom: 10%;">Province</p>
                            </div>
                            <div class="uk-margin">
                                <p style="padding-bottom: 5%;">District</p>
                            </div>
                            <div class="uk-margin">
                                <p style="padding-bottom: 10%;">Zipcode</p>
                            </div>
                            <div class="uk-margin">
                                <p>Address</p>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body" style="width: 120%; margin-left: -15%;box-shadow: none; background-color: #F7F5F5;" >
                            <form>

                                <div class="uk-margin">
                                    <input class="uk-input uk-form-width-large" style="border-color: #E3866C;" type="text" placeholder="Large">
                                </div>
                            
                                <div class="uk-margin">
                                    <input class="uk-input uk-form-width-large" style="border-color: #E3866C;" type="text" placeholder="Large">
                                </div>
                            
                                <div class="uk-margin">
                                    <select class="uk-select" style="width: 100%; margin-left: 0%;border-color:#E3866C;">
                                        <option>01</option>
                                        <option>02</option>
                                    </select>
                                </div>
                            
                                <div class="uk-margin">
                                    <select class="uk-select" style="width: 100%; margin-left: 0%;border-color:#E3866C;">
                                        <option>01</option>
                                        <option>02</option>
                                    </select>
                                </div>
                                <div class="uk-margin">
                                    <input class="uk-input uk-form-width-large" style="border-color: #E3866C;" type="text" placeholder="Large">
                                </div>
                                <div class="uk-margin">
                                    <textarea class="uk-textarea" rows="5" placeholder="Textarea" style="border-color: #E3866C;"></textarea>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>   
                <p uk-margin style="padding-top: 3%;margin-left: 40%;">
                    <a class="uk-button uk-button-default" href="#" style="border-color: #E3866C; background-color: #E3866C;color: white; font-size: 1.2em;border-radius: 2vh;padding: 2% 13%;">save</a>
                </p>
            </div>
        </div>
            
          
    </body>
</html>

PikPay/shop/templates/shop/mobile/page_beauty.html
{% extends 'shop/mobile/base.html' %}
{% load static %}
{% block title %} Toy {% endblock title %}



{% block content %}

	<div>
		<img src="{% static 'img/beauty-banner.png' %}"  alt="...">
	</div>
	<div class="uk-child-width-1-3@s uk-text-center uk-grid-match" style="width: 70%; margin-left: 25%;margin-top: 8.5%;" uk-grid uk-height-match="target: > div > .uk-card" >
		{% for p in product %}
			<a href="{% url 'shop:product' p.pk %}">
				<div>
					<div class="uk-card uk-card-default uk-card-body" style="background-color: #F7F5F5;">
					<br>
					<div style="padding-top: 5%;">
						<div class="uk-height-small uk-card uk-card-default uk-card-body uk-flex uk-flex-center uk-flex-middle" style="box-shadow: none;padding: 0% ;background-color: #F7F5F5;">
						<img src="{{p.photo.first.file.url}}" alt="..."> 
						</div>
					</div>
					<br>
					<br>{{p.name}}
					<br><span style="float: left; color: #ED796D; padding-left: 2%;">฿ {{p.price}}</span>
					</div>
				</div>
			</a>
		{% endfor %}
	</div>

{% endblock content %}

PikPay/shop/templates/shop/mobile/page_fashion.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/catagory2.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <script src="{% static 'js/fc54792532.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" type="text/css"/>

        <!-- UIkit JS -->
        <script src="{% static 'js/uikit.min.js' %}"></script>
        <script src="{% static 'js/uikit-icons.min.js' %}"></script>
        <title>Catagory</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'img/logofinal.png' %}">
    </head>
    <body>
    <body>
        <style>
        </style>
        <a href="" class="back-button">< HOME</a>
        
        <div class="beaytymenu-background">
          <div class="uk-child-width-expand@s" uk-grid style="padding-top: 5%; padding-left: 3%;">
            <div class="uk-grid-item-match">
                <div class="uk-margin">
                    <form class="uk-search uk-search-default">
                        <span uk-search-icon></span>
                        <input class="uk-search-input" type="search"  style="background-color: white; border-radius: 2vh; width: 280%; padding-top: 15%; padding-bottom: 15%; " placeholder="Search..." id="searchbox" onkeyup="onKeyupHandler(event)" value={{search_key}}>
                    </form>
                  <div class="autocomplete" uk-dropdown="mode: click">
                    <ul class="uk-nav uk-dropdown-nav suggestions">
                        <li>ไม่มีคำแนะนำ</li>
                    </ul>
                  </div>
                </div>
             </div>
            <div class="heart">
                <nav class="navbar navbar-light bg-black">
                        <a  href="{% url 'shop:myfavourite' %}">
                            <img  src="{% static 'img/heart_PNG51335.png' %}" width="20%" style="margin-left: 60%; margin-top: -5%;" alt="">
                        </a>
                </nav>
            </div>
          </div>
        </div>
        
        <div >
	<div>
			<img src="{% static 'img/fashion-banner.png' %}"  alt="...">
		</div>
		<div class="uk-child-width-1-3@s uk-text-center uk-grid-match" style="width: 70%; margin-left: 25%;margin-top: 8.5%;" uk-grid uk-height-match="target: > div > .uk-card" >
			{% for p in product %}
        <a href="{% url 'shop:product' p.pk %}" class="">
          <div>
            <div class="uk-card uk-card-default uk-card-body" style="background-color: #F7F5F5;">
            <br>
            <div style="padding-top: 5%;">
              <div class="uk-height-small uk-card uk-card-default uk-card-body uk-flex uk-flex-center uk-flex-middle" style="box-shadow: none;padding: 0% ;background-color: #F7F5F5;">
              <img src="{{p.photo.first.file.url}}" alt="..."> 
              </div>
            </div>
            <br>
            <br>{{p.name}}
            <br><span style="float: left; color: #ED796D; padding-left: 2%;">฿ {{p.price}}</span>
            </div>
          </div>
        </a>
			{% endfor %}
	</div> 

          

              
              
            <div class="" style="margin-top: -155.0%;">
              <a href="{% url 'shop:justforyou' %}">
                <img src="{% static 'img/justforu.png' %}" width="20%"  alt="...">
              </a>
              <br>
              <a href="{% url 'shop:healthandbeauty' %}">
                <img src="{% static 'img/health.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
              <br>
              <a href="{% url 'shop:electronics' %}">
                <img src="{% static 'img/elec.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
              <br>
              <a href="{% url 'shop:homeandlifestyle' %}">
                <img src="{% static 'img/home.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
              <br>
              <a href="{% url 'shop:fashion' %}">
                <img src="{% static 'img/fashion.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
              <br>
              <a href="{% url 'shop:sportsandtravel' %}">
                <img src="{% static 'img/sport.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
              <br>
              <a href="{% url 'shop:electronics' %}">
                <img src="{% static 'img/pets.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
              <br>
              <a href="{% url 'shop:toys' %}">
                <img src="{% static 'img/toy.png' %}"  style="width: 20%; margin-top: 0%;" alt="...">
              </a>
            </div>
        </div>  
          

        
        <div class="fixed-bottom">
          <div class="uk-grid-collapse uk-child-width-expand@s uk-text-center uk-margin-large-top" uk-grid>
            <div>
                <div class="uk-background-muted ">
                   <a class="home-button" href="{% url 'shop:home' %}">
                  <img src="{% static 'img/home1.png' %}"  width="100%" alt="...">
                </a>
              </div>
            </div>
            <div>
                <div class="uk-background-muted">
                  <a class="order-button" href="{% url 'shop:fashion' %}">
                    <img src="{% static 'img/cata1.png' %}"  width="100%" alt="...">
                </a>
                </div>
            </div>
            <div>
                <div class="uk-background-muted">
                  <a href="{% url 'shop:mycart' %}">
                    <img src="{% static 'img/order1.png' %}"  width="100%" alt="...">
                  </a>
                </div>
            </div>
            <div>
              <div class="uk-background-muted">
                <a href="{% url 'shop:profile' %}">
                  <img src="{% static 'img/pikpay1.png' %}"  width="100%" alt="...">
                </a>
            </div>
          </div>
        </div>
        </div>
         
    </body>
    <script src="{% static 'js/axios.js' %}"></script>
    <script>
      search().then(product => renderSuggestionList(product))
            function search() {
                let searchText = document.querySelector('#searchbox').value

                return axios.get(`/api/v1/product/?format=json&search=${searchText}`)
                .then(response => response.data)
                .catch(error => console.error(error))
            }

            function onKeyupHandler(e) {
                if (e.keyCode === 13) {
                    search().then(product => renderListedPeople(product))
                } 
                else {
                    search().then(product => renderSuggestionList(product))
                }
            }
              function searchBySuggestion(name, last_name) {
                document.querySelector('#searchbox').value = `${name} ${last_name}`

                search().then(people => renderListedPeople(people))
            }
            function renderSuggestionList(product) {
                console.log(product)
                let renderSuggestionList = ''

                if (product.results.length != 0) {
                    product.results.forEach(function(p){
                        renderSuggestionList += `
                                    <li>
                                        <a href="/search/?search=${p.name}">
                                            ${p.name}
                                        </a>
                                    </li>
                                `
                    });
                }
                else {
                renderSuggestionList = '<li>ไม่มีคำแนะนำ</li>'
                }

                let suggestionDOM = document.querySelector('.suggestions')
                suggestionDOM.innerHTML = renderSuggestionList
            }
            function getBuck(){
                return axios.get(`/shop/api/mybuck/`).
                then(response => response.data)
                .catch(error => console.error(error))
            }
            function bucket(){
                getBuck().then(data=>renderBuck(data))
            }
            function renderBuck(data){
                console.log(data)
                var renderText = ''
                var count=0
                var total_price =0
                if(data.length!=0){
                    data.forEach(d=>{
                        // console.log(d);
                        renderText += `<li>
                                <div class="uk-child-width-expand@s uk-margin-remove" uk-grid> 
                                    <div class="uk-padding-remove " id="img1"><img src="${d.image}"></div>
                                    <div class="uk-padding-remove uk-display-block"> 
                                        <h1>${d.name}</h1><br>
                                        <div class="uk-display-inline">
                                            <p> ${d.amount} </p>
                                           
                                        </div>
                                    </div>
                                </div>
                                <div class="uk-text-right" >
                                    <a onclick="del_buck(${d.id})">remove</a>
                                    <br>
                                    <h2>฿ ${d.price}</h2>
                                </div>
                            </li>`
                        
                        count+=1
                        total_price+=d.price
                    })
                }
                document.getElementById('cart_item').innerHTML = renderText;
                document.getElementById('count').innerHTML = count
                document.getElementById('total_price').innerHTML = total_price
            }
            function del_buck(pk){
                axios.get(`/del_bucket/${pk}`).
                then(response => response)
                .catch(error => console.error(error))
                bucket()
            }

    </script>
</html>

PikPay/shop/templates/shop/mobile/page_justforu.html
{% extends 'shop/mobile/base.html' %}
{% load static %}
{% block title %} Pet {% endblock title %}



{% block content %}

	<div>
		<img src="{% static 'img/justforu-banner.png' %}"  alt="...">
	</div>
	</div>
	<div class="uk-child-width-1-3@s uk-text-center uk-grid-match" style="width: 70%; margin-left: 25%;margin-top: 8.5%;" uk-grid uk-height-match="target: > div > .uk-card" >
		{% for p in product %}
			<a href="{% url 'shop:product' p.pk %}" class="">
				<div>
					<div class="uk-card uk-card-default uk-card-body" style="background-color: #F7F5F5;">
					<br>
					<div style="padding-top: 5%;">
						<div class="uk-height-small uk-card uk-card-default uk-card-body uk-flex uk-flex-center uk-flex-middle" style="box-shadow: none;padding: 0% ;background-color: #F7F5F5;">
						<img src="{{p.photo.first.file.url}}" alt="..."> 
						</div>
					</div>
					<br>
					<br>{{p.name}}
					<br><span style="float: left; color: #ED796D; padding-left: 2%;">฿ {{p.price}}</span>
					</div>
				</div>
			</a>
		{% endfor %}
	</div>

{% endblock content %}