PikPay/PikPay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from api.routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('auth/',include('authen.urls')),
    path('',include('shop.urls')),
    path('api/v1/', include(router.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PikPay/shop/urls.py
from django.urls import path
from .views import *
# from .views import home,homeandlifestyle,fashion,healthandbeauty,sportsandtravel,groceriesandpets,toys,electronics,profile,sell

app_name = 'shop'

urlpatterns = [
    path('',home,name='home'),
    path('homeandlifestyle/',homeandlifestyle,name='homeandlifestyle'),
    path('fashion/',fashion,name='fashion'),
    path('healthandbeauty/',healthandbeauty,name='healthandbeauty'),
    path('sportsandtravel/',sportsandtravel,name='sportsandtravel'),
    path('groceriesandpets/',groceriesandpets,name='groceriesandpets'),
    path('toys/',toys,name='toys'),
    path('electronics/',electronics,name='electronics'),
    path('justforyou/',justforyou,name='justforyou'),
    path('profile/',profile,name='profile'),
    path('shipping-address/',shippingaddress,name='shippingaddress'),
    path('sellverify/',sellverify,name='sellverify'),
    path('sellhome/',sellhome,name='sellhome'),
    path('mysell/',mysell,name='mysell'),
    path('sellerorder/<int:pk>',sellerorder,name='sellerorder'),
    path('seller_confirm/<int:pk>',seller_confirm,name='seller_confirm'),
    path('myproduct/',myproduct,name='myproduct'),
    path('addproduct/',addproduct,name='addproduct'),
    path('sellwallet/',sellwallet,name='sellwallet'),
    path('product/<int:pk>',product,name='product'),
    path('editprofile/',editprofile,name='editprofile'),
    path('creditcard/',creditcard,name='creditcard'),
    path('del_card/<int:pk>',delete_card,name='delete_card'),
    path('order/',order,name='order'),
    path('cancle_order/<int:pk>',cancle_order,name='cancle_order'),
    path('del_shippingaddr/<int:pk>/<str:page>',del_shippingaddress,name='del_shippingaddress'),
    path('set_dault_shippingaddress/<int:pk>/<str:page>',set_dault_shippingaddress,name='set_dault_shippingaddress'),
    path('reviewproduct/<int:pk>',reviewproduct,name='reviewproduct'),
    path('myfavourite/',myfavourite,name='myfavourite'),
    path('add_favorite/<int:pk>',add_favorite,name='add_favorite'),
    path('mycart/',mycart,name='mycart'),
    path('shoppinginfo/',shoppinginfo,name='shoppinginfo'),
    path('seller/',seller,name='seller'),
    path('search/',search,name='search'),
    path('shop/api/mybuck/',mybucket,name='mybucket'),
    path('del_bucket/<int:pk>',del_bucket,name='del_bucket'),
    path('confirmshipping/',confirmshipping,name='confirmshipping'),
    path('tracking/<int:pk>',tracking,name='tracking'),
    path('editaddress/',editaddress,name='editaddress'),
    path('upload_product_pic/',upload_picture,name='upload_pic'),
    path('editproduct/<int:pk>',edit_product,name='edit_product'),
    path('review/',review,name='review'),
    path('confirm_order/<int:pk>',confirm_order,name='confirm_order'),
    path('shop_product/<int:pk>',shop_product,name='shop_product'),
    path('del_product/<int:pk>',del_product,name='del_product'),
]

PikPay/shop/models.py
from django.db import models
from django.contrib.auth.signals import user_logged_in
from authen.models import Account,Address
import re

# Create your models here.

class Bank(models.Model):
    short_en = models.CharField(max_length=5)
    name = models.CharField(max_length=100)

    def __str__(self):
        return "{}-{}".format(self.short_en,self.name)
    

class Seller(models.Model):
    account = models.OneToOneField(Account,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=200)
    shop_name = models.CharField(max_length=100)
    citizen_id = models.CharField(max_length=13)
    bank = models.ForeignKey(Bank,on_delete=models.SET_NULL,null=True)
    account_name = models.CharField(max_length=200)
    account_number = models.CharField(max_length=20)
    total_income = models.PositiveIntegerField()
    is_verify = models.BooleanField()
    def __str__(self):
        return self.shop_name

class Buyer(models.Model):
    account = models.OneToOneField(Account,on_delete=models.SET_NULL,null=True)
    total_buyer = models.PositiveIntegerField()
    def __str__(self):
        return self.account.user.username

class Tags(models.Model):
    name = models.CharField(max_length=100)
    types = models.CharField(max_length=100)
    def __str__(self):
        return "{}-{}".format(self.name,self.types)

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Picture(models.Model):
    file = models.ImageField()
    def __str__(self):
        return self.file.name
        
class Logistic(models.Model):
    name = models.CharField(max_length=100)
    detail = models.TextField()
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class Product(models.Model):
    seller = models.ForeignKey(Seller,on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    description = models.TextField()
    price = models.PositiveIntegerField()
    photo = models.ManyToManyField(Picture)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    tag = models.ManyToManyField(Tags)
    sales = models.PositiveIntegerField()
    logistic = models.ForeignKey(Logistic,on_delete=models.SET_NULL,null=True)
    total_amount = models.PositiveIntegerField()
    is_use = models.BooleanField(default=True)
    
    def __str__(self):
        return "{} {}-{}".format(self.pk,self.name,self.seller)

class Detail(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    model = models.CharField(max_length=100)
    amount = models.PositiveSmallIntegerField()
    width = models.PositiveSmallIntegerField()
    heigth = models.PositiveSmallIntegerField()
    depth = models.PositiveSmallIntegerField()
    weigth = models.PositiveSmallIntegerField()
    is_use = models.BooleanField(default=True)

    def __str__(self):
        return "{}-{}".format(self.product.name,self.model)

class CreaditCard(models.Model):
    account = models.ForeignKey(Account,on_delete=models.CASCADE)
    card_number = models.CharField(max_length=20)
    hold_name = models.CharField(max_length=200)
    expire = models.DateField()
    secure = models.CharField(max_length=10)
    KIND_CHOICES = [
        ('en','electron'),
        ('mo','maestro'),
        ('dt','dankort'),
        ('it','interpayment'),
        ('uy','unionpay'),
        ('va','visa'),
        ('md','mastercard'),
        ('ax','amex'),
        ('ds','diners'),
        ('dr','discover'),
        ('jb','jcb'),
        ('nk','unknown'),
        ('ba','bank'),
        ('cd','cod'),
    ]
    kind = models.CharField(max_length=2,choices=KIND_CHOICES,default='nk')

    def creadit_card_type(creaditcard_no):
        patterns={'mo': '^(5018|5020|5038|5612|5893|6304|6759|6761|6762|6763|0604|6390)\d+$',
                'en': '^(4026|417500|4405|4508|4844|4913|4917)\d+$',
                'dt': '^(5019)\d+$',
                'it': '^(636)\d+$',
                'uy': '^(62|88)\d+$/',
                'va': '^4[0-9]{12}(?:[0-9]{3})?$',
                'md': '^5[1-5][0-9]{14}$',
                'ax': '^3[47][0-9]{13}$',
                'ds': '^3(?:0[0-5]|[68][0-9])[0-9]{11}$',
                'dr': '^6(?:011|5[0-9]{2})[0-9]{12}$',
                'jb': '^(?:2131|1800|35\d{3})\d{11}$'
        }
        for pattern in patterns:
            if re.match(patterns[pattern],creaditcard_no):
                return pattern
            else:
                return 'uk'
    

class Transaction(models.Model):
    product = models.ForeignKey(Detail,on_delete=models.SET_NULL,null=True)
    buyer = models.ForeignKey(Buyer,on_delete=models.CASCADE)
    amount = models.PositiveSmallIntegerField()
    price = models.PositiveIntegerField()
    payment_method = models.ForeignKey(CreaditCard,on_delete=models.SET_NULL,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    logistic_company = models.ForeignKey(Logistic,on_delete=models.SET_NULL,null=True)
    tracking_id = models.CharField(max_length=20)
    address = models.ForeignKey(Address,on_delete=models.SET_NULL,null=True)
    STATUS_CHOICES = [
        ('no','new order'),
        ('pa','paid'),
        ('sc','seller confirm'),
        ('se','sent'),
        ('cf','customer confirm'),
        ('re','waiting review'),
        ('ss','sucess'),
        ('cc','cancle'),
    ]
    status = models.CharField(max_length=2,choices=STATUS_CHOICES,default='no')

    # def __str__(self):
    #     return

class Bucket(models.Model):
    buyer = models.ForeignKey(Buyer,on_delete=models.CASCADE)
    product = models.ForeignKey(Detail,on_delete=models.CASCADE)
    amount = models.PositiveSmallIntegerField()
    is_use = models.BooleanField(default=True)

class Review(models.Model):
    transaction = models.ForeignKey(Transaction,on_delete=models.SET_NULL,null=True)
    buyer = models.ForeignKey(Buyer,on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    star = models.PositiveSmallIntegerField()
    description = models.TextField(null=True,blank=True)
    photo = models.ManyToManyField(Picture,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

class TitleReport(models.Model):
    title = models.CharField(max_length=200)
    KIND_CHOICES = [
        ('y','pikpay'),
        ('p','product'),
        ('s','seller'),
        ('b','buyer')
    ]
    kind = models.CharField(max_length=1,choices=KIND_CHOICES,default='y')

    def __str__(self):
        return "{}-{}".format(self.kind,self.title)

class Report(models.Model):
    user = models.ForeignKey(Account,on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    title = models.ForeignKey(TitleReport,on_delete=models.SET_NULL,null=True)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class Favorite(models.Model):
    user = models.ForeignKey(Buyer,on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    is_use = models.BooleanField(default=False)

class FlashSale(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    date = models.DateField()
    discount = models.PositiveSmallIntegerField()
    is_flashsale = models.BooleanField()

def logged_in_handle(sender, user, request, **kwargs):
    account = Account.objects.get(user=request.user)
    buyer = Buyer.objects.filter(account=account)
    if not buyer.exists():
        Buyer.objects.create(
            account = account,
            total_buyer = 0
        )
user_logged_in.connect(logged_in_handle)

PikPay/shop/templates/shop/web/Fashion.html
{% extends 'shop/web/base.html' %}
{% load static %}
{% block title %} Fashion {% endblock title %}
{% block content %}
    <body>  
        <!-- Data Zone -->
        <div class="uk-container-expand" style="background-color: #FFFBE3; min-height: 100vh; max-width: 100%;">
            <!-- Top Banner -->
            <div class="uk-padding-remove-horizontal banner" uk-slideshow="autoplay: true; autoplay-interval: 4500; pause-on-hover: true; min-height: 300; max-height: 500">
                <ul class="uk-slideshow-items ">
                    <li>
                        <img src="{% static 'img/banner1.jpg' %}" alt="" uk-cover>
                    </li>
                    <li>
                        <img src="{% static 'img/shipfree.png' %}" alt="" uk-cover>
                    </li>
                </ul>
                <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>
    
                <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>
            </div>

            <!-- Item Show -->
            <div class="showitem uk-margin-auto">
                <h1 style="border-bottom: 3px solid #B15656; color: #833232;"><img src="{% static 'img/fashion.png' %}" width="8%" height="8%" alt="" style="margin-right: 2%;"> FASHION</h1>       
                <div class="uk-grid-small uk-child-width-1-6 uk-text-center uk-margin-small uk-padding" uk-grid>
                    <!-- <div>
                        <div class="uk-card uk-card-default uk-card-body">Item</div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body">Item</div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body">Item</div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body">Item</div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body">Item</div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-default uk-card-body">Item</div>
                    </div> -->
                    {% for p in product %}
                        <li>
                            <a id="itemcard" href="{% url 'shop:product' p.pk %}">
                                <div class="uk-card uk-card-default uk-card-body uk-padding-small">                                                                    
                                    <div class="uk-height-medium uk-flex uk-flex-center uk-flex-middle uk-background-cover" data-src="{{p.photo.first.file.url}}" uk-img></div>
                                    <div class="uk-text-center">
                                        <p id="nametag">{{p.name}}</p>
                                        <p id="price">{{p.price}}฿</p>
                                    </div>                                                                
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </div>         
            </div>
        </div>
        {% if product.has_other_pages %}
            <ul class="uk-pagination uk-flex-center" uk-margin>
                {% if product.has_previous %}
                    <li><a href="?page={{ users.previous_page_number }}"><span uk-pagination-previous></span></a></li>                    
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}

                {% for i in product.paginator.page_range %}
                    {% if product.number == i %}
                        <li class="uk-active"><span>{{ i }}</span></li>                       
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if product.has_next %}
                    <li><a href="?page={{ users.next_page_number }}"><span uk-pagination-next></span></a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    </body>
{% endblock content %}

PikPay/shop/templates/shop/web/Review_product.html
{% extends 'shop/web/base.html' %}
{% load static %}
{% block title %} Order {% endblock title %}
{% block content %}
    <body>
        <!-- Data Zone -->
        <div class="uk-container-expand uk-padding-large" style="background-color: #FFFBE3; min-height: 100vh; max-width: 100%;">       
            <div class="profile uk-margin-auto " uk-grid>
                <div class="uk-width-1-4 uk-padding-large uk-padding-remove-right">     
                    <div uk-grid>
                        <div class="uk-width-1-2">                            
                            {% if profile.image %}
                                <img class="profilepic" src="{{ profile.image.url }}" alt="Profile" height="100%" width="100%">
                            {% else %}
                                <img class="profilepic" src="{% static 'img/Profile.png' %}" alt="Profile" height="100%" width="100%">
                            {% endif %}
                        </div> 
                        <ul class="uk-list uk-width-1-2">
                            <p class="wordWrap" id="usernameprofile">{{profile.user}}</p>
                            <p id="memberstatus">Membership</p>
                        </ul>                        
                    </div>
                    <ul class="uk-list uk-margin-medium-top uk-link-reset" style="font-size: 1.8rem;">
                        <li class="profileicon">
                            <a href="{% url 'shop:profile' %}"><i class="las la-user"></i>  Profile</a>
                        </li>
                        <li class="profileicon">
                            <a href="{% url 'shop:shippingaddress' %}"><i class="las la-home"></i>  Shipping Address</a>
                        </li>
                        <li class="profileicon">
                            <a href="{% url 'shop:creditcard' %}"><i class="las la-credit-card"></i>  Credit Card</a>
                        </li>
                        <li class="profileicon">
                            <a href="{% url 'shop:order' %}"><i class="las la-receipt"></i>  Order</a>
                        </li>
                        <li class="profileicon">
                            <a href="{% url 'shop:myfavourite' %}"><i class="las la-heart"></i>  My favourite</a>
                        </li>
                        <li class="profileicon">
                            <a href="{% url 'shop:review' %}"><i class="lar la-thumbs-up"></i>  My review</a>
                        </li>
                    </ul>
                </div>

                <div class="uk-width-3-4 uk-padding-large">
                    <div style="height: 100%; width: 100%; background-color: #FAFAFA;">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="uk-padding-large">
                            <h2 style="border-bottom: 2px solid #FF9C9C; padding-bottom: 2%;">My Review</h2>
                            
                            <!-- Show product and add rating-->                                                       
                            <div class="uk-width-expand uk-card reviewproduct uk-padding-small uk-flex-inline">
                                <img src="{{order.product.product.photo.first.file.url}}" alt="product" id="productstock">
                                <div class="uk-width-expand uk-text-middle uk-margin-medium-left uk-margin-auto-vertical">
                                    <h4>{{order.product}}</h4>
                                    <p>Price : {{order.price}} ฿</p>
                                    <p>Quantity : {{order.amount}}</p>
                                    <h5 style="margin-top: 3vh; margin-bottom: 1vh;">Give Rating</h5>
                                {% if reviewed == False %}
                                    <!-- Hide when already review -->
                                    <div>                                                  
                                        <div id="full-stars-example-two">
                                            <div class="rating-group">                                            
                                                <label aria-label="1 star" class="rating__label" for="rating3-1"><i class="rating__icon rating__icon--star las la-star"></i></label>
                                                <input class="rating__input" name="rating3" id="rating3-1" value="1" type="radio">
                                                <label aria-label="2 stars" class="rating__label" for="rating3-2"><i class="rating__icon rating__icon--star las la-star"></i></label>
                                                <input class="rating__input" name="rating3" id="rating3-2" value="2" type="radio">
                                                <label aria-label="3 stars" class="rating__label" for="rating3-3"><i class="rating__icon rating__icon--star las la-star"></i></label>
                                                <input class="rating__input" name="rating3" id="rating3-3" value="3" type="radio">
                                                <label aria-label="4 stars" class="rating__label" for="rating3-4"><i class="rating__icon rating__icon--star las la-star"></i></label>
                                                <input class="rating__input" name="rating3" id="rating3-4" value="4" type="radio">
                                                <label aria-label="5 stars" class="rating__label" for="rating3-5"><i class="rating__icon rating__icon--star las la-star"></i></label>
                                                <input class="rating__input" name="rating3" id="rating3-5" value="5" type="radio">
                                            </div>
                                        </div>
                                    </div>
                                {% else %}
                                    <!-- Show when already review -->
                                    <div>
                                        <p class="uk-margin-remove" id="ratestar" style="padding: 0 0.1em; font-size: 2rem;"></p>
                                    </div>
                                {% endif %}
                                    
                                </div>
                            </div>

                            <!-- Add review detail here (disable when alredy review)-->
                            <div class="uk-width-expand uk-card reviewdetail uk-padding-small uk-flex-inline uk-margin-medium-top">
                                <div class="uk-form-horizontal" >
                                    {% csrf_token %}
                                    <div class="uk-margin">
                                        <label class="uk-form-label uk-margin-auto-vertical" for="form-horizontal-text">Comment</label>
                                        <div class="uk-form-controls">
                                            {% if reviewed %}
                                                <textarea class="uk-textarea uk-width-5-6" rows="5" id="reviewdetail" placeholder="Add review detail" name="comment" disable>{{review.description}}</textarea>
                                            {% else %}
                                                 <textarea class="uk-textarea uk-width-5-6" rows="5" id="reviewdetail" placeholder="Add review detail" name="comment"></textarea>
                                            {% endif %}
                                        </div>
                                    </div>

                                    {% if reviewed == False %}
                                        <div class="uk-margin">
                                            <label class="uk-form-label uk-margin-auto-vertical" for="form-horizontal-text">Review photo</label>
                                            <div class="uk-form-controls">
                                                <div class="js-upload uk-placeholder uk-text-center uk-width-5-6">
                                                    <span uk-icon="icon: cloud-upload"></span>
                                                    <span class="uk-text-middle">Upload picture by dropping them here or</span>
                                                    <div uk-form-custom>
                                                        <input type="file" multiple>
                                                        <span class="uk-link">selecting one</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                    <progress id="js-progressbar" class="uk-progress" value="0" max="100" hidden></progress>
                                </div>                    
                                
                                                                
                            </div>
                            <input type="text" name="picture" id="pic" hidden>
                            <!-- submit button (hidden when alredy review) -->
                            {% if reviewed == False %}
                                <div class="uk-width-expand uk-text-right uk-margin-medium-top">
                                    <button id="submitreview" type="submit">submit</button>
                                </div>
                            {% endif %}
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>

    <!-- Uikit upload script -->
    <script>

        var bar = document.getElementById('js-progressbar');
        let list_pic = []
        UIkit.upload('.js-upload', {
    
            url: '{% url 'shop:upload_pic' %}',
            multiple: true,
            beforeSend: function () {
                console.log('beforeSend', arguments);
            },
            beforeAll: function () {
                console.log('beforeAll', arguments);
            },
            load: function () {
                console.log('load', arguments);
            },
            error: function () {
                console.log('error', arguments);
            },
            complete: function () {
                console.log('complete', arguments);
                let res = arguments[0].response
                console.log(res)
                list_pic.push(res)
            },
    
            loadStart: function (e) {
                console.log('loadStart', arguments);
    
                bar.removeAttribute('hidden');
                bar.max = e.total;
                bar.value = e.loaded;
            },
    
            progress: function (e) {
                console.log('progress', arguments);
    
                bar.max = e.total;
                bar.value = e.loaded;
            },
    
            loadEnd: function (e) {
                console.log('loadEnd', arguments);
    
                bar.max = e.total;
                bar.value = e.loaded;
            },
    
            completeAll: function () {
                console.log('completeAll', arguments);
                document.getElementById('pic').value = list_pic
                setTimeout(function () {
                    bar.setAttribute('hidden', 'hidden');
                }, 1000);
    
                alert('Upload Completed');
            }
    
        });
    
    </script>

    <script>
        var text = "";
        var rate = {{review.star}}; //Ratting from user
        var j=0;
        for (var i = 0; i < 5; i++) {
            if(j<rate) {
                text += '<i class="lar la-star starchecked"></i>';
                j++;
            }
            else {
                text += '<i class="lar la-star star"></i>';
            }                    
        }
        document.getElementById('ratestar').innerHTML = text;        
    </script>
    </body>
{% endblock content %}

PikPay/shop/templates/shop/web/base_sell.html
<html>
{% load static %}

<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">         -->
        <link rel="stylesheet" href="{% static 'css/line-awesome.min.css' %}">
        <script src="{% static 'js/uikit.min.js' %}"></script>
        <script src="{% static 'js/uikit-icons.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/pikpay.css' %}" type="text/css"/>
        <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" type="text/css"/>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
        <title>{% block title %}  {% endblock title %}</title>        
</head>
<body>
    <nav class="sellernavbar" uk-navbar>
        <div class="uk-navbar-left uk-margin-medium-left">
            <a href="{% url 'shop:home' %}" class="uk-logo uk-width-small" >
                <img src="{% static 'img/logo.png' %}" alt="logo PikPay" height="75%" width="75%">
            </a>
            <a href="{% url 'shop:sellhome' %}">
                <h1>PIKPAY SELLER</h1>
            </a>
            <a href="{% url 'shop:sellhome' %}">
                <h2>My shop</h2>
            </a>
            <a href="{% url 'shop:mysell' %}">
                <h2>My sales</h2>
            </a>
            <a href="{% url 'shop:myproduct' %}">
                <h2>Product</h2>
            </a>
            <a href="{% url 'shop:sellwallet' %}">
                <h2>Wallet</h2>
            </a>
        </div>

        <div class="uk-navbar-right uk-margin-medium-right">
            <img src="{% static 'img/Profile.png' %}" alt="" height="120px" width="120px">
        </div>
    </nav>

    <!-- Body data -->
    {% block content %}
    {% endblock content %}
</body>
</html>